---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qanda-chatbot-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgBXWOTxSALLQPfxO+GbDUz1bEOH8sRa5j01gYYn/OoW8iTZd2myGnu4eKq6Gri6tuSFxnvYg5Eojxv2W7b/TkdIWniELCrbkNONljSekgHGg9NP2bKHoAw9CK6pufw/fddIrQNdNdc11OHunJZ/+JScmDTbOvsq+qKYfLrKiVswcyGm08mcG3she2JwAcHYSjOiPLlV+4Fe2vSXMDdZCTxgWU1v3H1j541UepydnTEMXKGRfU/FHqT1E77fFgkIuIsLaXPSRKnHQ1fK+cwy676KonelAVpWPP6FHXR5suj5jYRXJVCvp3qXNWb0tXBEqcR/o+xvJ/bbtgW0U1wA/6HdTi9VAOJ4ypiaLaVopEGtTs1q7vFC29rHSsio+C31zmD7I6h74t0kWaa5iB9lNyaHma+Ivn8Szxg0RiZCIuZLEB18u42onCMKFnXMVZNzhZTBixYMatdHEXJcLCaqv2H9H924nb5SKZVMs8mEDB/flZwfup0A6v2CHnbfIFXDXbnf8YQqqcdKnXOwAdQvK8VJ2c7ANcPMy3XGy7XpoTfb/YkqJaIwV27DnZHzgqE5FBheRo0pjLUUczuaWlrHrZ48lIvumHZtd9wzTdG3PJg+AIBe8XZJLwo5/LSFtEAtqNswqHKG4Qbr31S0nfqeryLw6uzRZZEq4Kk/bcGcPL0Ot6fzuOkkkzjk0tDffLFFIt3jcj8FtSOOdv4euAa3OwVD/Barqbxp61psieDe0fW3SvwxmzY6Os5+xcX5OkIED/wr0dEXSm33vA7JCzE2NmEenL0XfM2fvfHV/9xVsdaiuuFIFrp/X4dPuHGoIzwgze7fQbl8hI84OnTCA6mXxVsPbhElQ57cVkv/0cm1oVraRp+rWMRExmEfgyQvQRnxEiy92wr51cslMdxUrAP9IrHvoqhKOhWVaOwk/e8+wTuOLDGbHvde3PdwRpUfORZ3/44QIGPN/dnKcFfRgiDwfb/pSGqB0W73fWZuqReOd7xiETxZ6vcMmhq9cLaVlGLReI77yjeEExj4dtg8J9jBR2tZ49cZu9TbeMbGWt40YO2ObODQld4C+YSc4SZw/HcB/NqSQwNQYeH9ueryXZqlv29mxhsitu9WunyYdPpzoXjn5yd/jyHsqzU7UFCKfFIyU3L56mSZME1z+au8tuHtowsSTXWceXUxJw7Z0EZr+TyC7AnqW+0YAU6N21qVP42n0rPX49C4vZYK4GHa6phEng2vzZevdlfA18ErmN+KxSYv3tLHtpFQ3HcsH72D+h+H+tJwR/QDyN2h0PLXpFBApajF5I5MDk1s3KKPJ4wLYc/NnO4ucHCGLl1rm6BVAbHxfLQhyLe2yfWGcCg3RkMBrO1p5Lvln7swxKwq1I+UrdE/3HPLhxZ8eaTgtIzgZmlUL2PzaRvco4HLNGvGrBmfHmJeQY3crvF6AbM=
  template:
    metadata:
      creationTimestamp: null
      name: qanda-chatbot-secrets
      namespace: default
    type: Opaque
